//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IEmployeeBusinessId } from './IEmployeeBusinessId';
import { Gender } from '../../../Core/Shared/Enums/Gender';

export interface ICreateEmployeeRequest
{
	firstName?: string;
	middleName?: string;
	lastName?: string;
	businessId: IEmployeeBusinessId;
	gender?: Gender;
	dob?: any;
}
