//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EmployeeType } from '../../../Core/Shared/Enums/EmployeeType';

export interface IImportResultResponse
{
	actionType: string;
	id: any;
	businessIdPersonnelNumber: string;
	businessIdType?: EmployeeType;
}
